### ISSUE TITLE
Nicer URLs :)

### ISSUE THREAD

**Issue by mikeal** [ProtoSchool/protoschool.github.io#105]
Currently, we're using hash based routing in Vue.js, which means that the URLs aren't as pretty as they could be :)

We could us Vue.js' [history mode](https://router.vuejs.org/guide/essentials/history-mode.html) but it's a little difficult to make it work with ghpages and/or Cloudflare.

One option would be to use history mode *and* create static pages for each resources, https://cli.vuejs.org/config/#pages. This would greatly improve our SEO but might increase our build times a bit.

**Comment by Frijol** [comment]
Was this resolved (possibly in https://github.com/ProtoSchool/protoschool.github.io/pull/103)? URLs appear to be very sensible from a user perspective at the moment

**Comment by terichadbourne** [comment]
@mikeal Was your "not pretty" assessment just related to the URLs all including "/#/" or did you have something else in mind as well?  Not that this convo will be affected by whether or not we move to VuePress (see #141).

**Comment by terichadbourne** [comment]
@zebateira 

Note that these issues are probably all affected in some way by the choices we make here:
- Want to be able to create separate meta tags for social sharing on separate "pages" (#258)
- We haven't been able to use anchor tags to drop people down to specific content within a page because of the hash routing 
- We need to think about what will work best longer term when we're ready to host on IPFS (#18)

**Comment by terichadbourne** [comment]
Closing as @zebateira has just gotten us switched over to history mode (removing the hashes and setting up redirects) and transitioned to Netlify. This should unblock the SEO / metadata challenges (#258), enable anchor tags, and help with a future transition to IPFS & Fleek (#18). 🎉
