### ISSUE TITLE
Bug: nav menu isn’t responsive on mobile

### ISSUE THREAD

**Issue by momack2** [ProtoSchool/protoschool.github.io#122]
I tried protoschool on my iPhone 10 in Chrome and noticed some issues with responsive wrap - especially with the navigation menu at the top not responsively collapsing into a hamburger or something. I don’t believe this is device specific, but would show up on all sufficiently narrow mobile devices, but can give more detail if others can’t reproduce. Either a “more” Carey with a drop down menu for the items that don’t fit or a hamburger style would allow those menu items to be accessible without the weird scrolling.

**Comment by terichadbourne** [comment]
Thanks for the feedback, @momack2! I had noticed this too and documented it in #108. I'm going to do my best to come up with a quick fix before launch.

To me it seemed like the nav bar was the most obvious offender and that otherwise the non-lesson content was pretty accessible/responsive on mobile, but if you remember noticing anything else specific, do let me know.
