### ISSUE TITLE
IPLD Explorer not loading from Blog - Lesson 6 

### ISSUE THREAD

**Issue by RyanBRiley** [ProtoSchool/protoschool.github.io#125]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
eg https://proto.school/#/blog/06

**What's confusing about this lesson?**
Link to view correct result in IPLD explorer loads the explorer but the result is not viewable. It appears as though it is perpetually loading. 

**What other feedback would you like to share about ProtoSchool?**
Everything else has been great so far.

**Comment by terichadbourne** [comment]
Thanks for the catch, @RyanBRiley! I get the same perpetual loading symbol that you do. 

@mikeal Is it obvious to you why this isn't working, or should we be filing a bug in the [IPLD Explorer repo](https://github.com/ipfs-shipyard/ipld-explorer)? 

![image](https://user-images.githubusercontent.com/19171465/51096560-3c3c7980-178b-11e9-8bc2-9e8a735dace2.png)

**Comment by mikeal** [comment]
Nope, maybe @olizilla knows.

**Comment by olizilla** [comment]
this happens when there is an issue lazy loading the ipld dependency from the gateway, or when the in-browser js-ipfs hasn't managed to share the block created as part of the lesson with the preload nodes.

The link to the IPLD explorer has been removed from the success message, or at least, i don't see it. I suggest we close this issue out for now and keep an eye out for similar issues in the future.

**Comment by terichadbourne** [comment]
@olizilla I'm guessing you clicked the link above which goes to lesson 1 instead of lesson 6 which is the one in question and does have a link to IPLD explorer.  The correct lesson link is: https://proto.school/#/blog/06 and the IPLD Explorer link generated by submitting the right solution is: https://ipfs.io/ipfs/QmYJETQ15RAnKXoJxqpXzcvQ2DuQA35UHwJBTjTPCSs9Ky/#/explore/zdpuAkUysBpAE2yvWdLCBbUqXusYVe5kgFSS7YriyeLfA5F5d

I just tried again and still get the spinner. I must confess I'm enough of a beginner that your first paragraph is mostly gibberish to me, so I still don't understand whether there's a problem with this lesson, a problem with the IPLD Explorer, or neither. Any chance you'd have some time this week to give me a quick lesson on IPLD Explorer?
