### ISSUE TITLE
UX Bug: Triangle "play" button implies video content

### ISSUE THREAD

**Issue by Frijol** [ProtoSchool/protoschool.github.io#162]
**Describe the bug**
The little arrows by the lessons on the Tutorials page are typically used to indicate video content but are in this case simply links. This is misleading design.

![screen shot 2019-02-22 at 4 25 41 pm](https://user-images.githubusercontent.com/454690/53278543-b7fce080-36be-11e9-821a-52800167011e.png)

This greatly changes the context in which I would consume the content– e.g. I would scroll through a text-based page at a workplace or in a crowded cafe, but expecting video content, didn't click until I knew I could get out headphones/sit in a quiet place.

**Expected behavior**
Video iconography for videos only please! Simply removing the icon would solve the problem for me.

**Comment by terichadbourne** [comment]
Thanks for the UX feedback, @frijol! I totally understand your concern. 

This is part of a 3-part icon set that is meant to convey "not started," "in progress," and "completed." The two most prominent places where those icons are used are in the list of lessons within each tutorial, like so: 

![image](https://user-images.githubusercontent.com/19171465/53344216-24a2f580-38e0-11e9-874b-d0d803ce23a6.png)

and as a status in the exercise box, like so: 

![image](https://user-images.githubusercontent.com/19171465/53344233-35ec0200-38e0-11e9-8f8f-f3e6f8c1bc94.png)

I'd really prefer to keep some kind of "not yet started" icon so that we continue the system of there being a visual status indicator regardless of your status, but I would love to hear any ideas you have for other ways to represent "not started" visually.

**Comment by Frijol** [comment]
thanks for the explanation! I wonder if a little blue dot with nothing in it would convey the idea, like a quiet notification dot?

Trying to look for examples– the Messenger app does this for unread messages.

**Comment by fsdiogo** [comment]
> The little arrows by the lessons on the Tutorials page are typically used to indicate video content but are in this case simply links. This is misleading design.

Agreed, it is misleading.

Why not just keep the check icon in gray while the lesson is not passed?

**Comment by terichadbourne** [comment]
If there were two states, not passed and passed, then a non-colored version of the passed icon could make sense. I feel a little differently given that there are 3: not started, in progress, passed.

**Comment by fsdiogo** [comment]
I made a simple icon in Figma to replace the "play" icon:

![start](https://user-images.githubusercontent.com/33324750/57543820-59eea980-734d-11e9-8dc4-d25711125b53.png)
 
I think it works way better than the one we're using right now, as it doesn't imply that a video will be played and follows the overall appearance of the other ones.

Check how it looks in a page:

<img width="886" alt="Screenshot 2019-05-10 at 17 54 25" src="https://user-images.githubusercontent.com/33324750/57543613-bb624880-734c-11e9-9691-91607bf1376f.png">

I'll open a PR to close this issue if everyone agrees with this!

**Comment by terichadbourne** [comment]
I'm good with that plan! Thank you!
