### ISSUE TITLE
Feature: Accordion drop-down for lessons on tutorials page

### ISSUE THREAD

**Issue by NukeManDan** [ProtoSchool/protoschool.github.io#222]
From the [IPFS meeting today](https://github.com/ProtoSchool/roadmap/pull/8), I am sugessting a new minor feature:

**Is your feature request related to a problem? Please describe.**

https://proto.school/#/tutorials

This will get really cluttered as more tutorials are added with all the lessons linked out - a very long page indeed... :wink: . I suggest we collapse the lessons for each tutorial to clean this up inside a drop-down. 

**Describe the solution you'd like**
Accordion to expand each tutorial's lessons, to make it easier to explore from https://proto.school/#/tutorials , or (less optimal) removing the links to lessons directly, and only showing them in the sub-url for the specific tutorial (ex: https://proto.school/#/data-structures/ ) 

**Describe alternatives you've considered**
Remove lesson links on top level tutorial page.

**Comment by terichadbourne** [comment]
Thanks for the suggestion, @NukeManDan. The other option, as you mentioned, is to cut the detailed lesson descriptions from the tutorial listings on the "tutorials" landing page altogether 
This is only a reasonable possibility now because @fsdiogo created landing pages for each tutorial that show the lessons included in each: 

![image](https://user-images.githubusercontent.com/19171465/57545624-ecc91d00-7328-11e9-9b39-d122c4fc8bcb.png)

If we cut that detail from the tutorials page, we could use cards instead there like we do on the homepage: 
![image](https://user-images.githubusercontent.com/19171465/57545374-1afa2d00-7328-11e9-9f66-3df86f348e43.png)
However, clicking through to get the detail and clicking back might still be annoying. 

Ultimately when we have more content I think we'll end up organizing it into chunks or courses of tutorials that make sense together, so briefer entries will be needed, whether that's by using accordians or just excluding the lesson detail from that view.

[NodeSchool](https://nodeschool.io/#workshoppers) - which is admittedly different since the tutorials themselves aren't web-baed - surfaces just titles and brief descriptions: 

![image](https://user-images.githubusercontent.com/19171465/57545570-bdb2ab80-7328-11e9-8c6b-340964b79c99.png)

**Comment by terichadbourne** [comment]
Closing this one out as we just switched to cards on the tutorials page. Hoping this will surface more content near the top as @NukeManDan suggested and also make it easier to spot the changes when folks use our new course filter. 

![image](https://user-images.githubusercontent.com/19171465/87170130-efadfd80-c29e-11ea-84c6-55e589960603.png)
