### ISSUE TITLE
Audit other online coding education platforms

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#264]
Review existing online coding education platforms to see if there are any that fully support our needs, or which could be easily adapted to do so. This will inform a decision as to whether to continue adding features to our own custom platform or replace it with an embedded solution from elsewhere.

This is a nice-to-have for Q3, more likely to complete the review in Q4.

**Comment by terichadbourne** [comment]
@fsdiogo @olizilla and I started a bit of brainstorming today on what requirements might look like if we were to find a fully-featured platform to use instead of our custom solution: https://docs.google.com/document/d/17w9Ni1OP_jP6vhQthLD9ZNPvh19g2-PD0GCEr9sVYo4/edit?usp=sharing

We'll know more about options and what to look for after the research begins, so will plan to circle back once the exploration is underway.

**Comment by terichadbourne** [comment]
See https://github.com/ProtoSchool/protoschool.github.io/issues/140

**Comment by dominguesgm** [comment]
I started writing up some details on platforms I found that could be viable options. So far, I've only found ChainShot, which is the platform mentioned in #140. I'm still looking for alternatives.

The link to the document is [here](https://docs.google.com/document/d/10tcTF1P_5Fjblj4PJHcdqG2VgLrxT3pD9sLyaBTLEvU/edit?usp=sharing)

**Comment by erlend-sh** [comment]
I recommend taking a look at https://codesandbox.io/

It definitely fulfills some of your key requirements like embedding and it’s built by a funded team that’s trying to become self-sustaining. Several education features would need to be built as extensions though.

**Comment by NukeManDan** [comment]
don't discount the big guys. [This Article](https://skillcrush.com/2016/03/15/64-online-resources-to-learn-to-code-for-free/) is older, but highlights a lot of web IDE based learning platforms. 

Another from the ETH space is https://cryptozombies.io/ - a gamified way to learn solidity.

**Comment by dominguesgm** [comment]
@erlend-sh if I'm not mistaken, codesandbox would be a replacement for the monaco editor we're using, right? I've been trying it out and I'm having some issues importing the `ipfs` package in there, I don't know if I'm doing something wrong or if it's a limitation of the platform.

I'm looking over some of the platforms in that list, @NukeManDan , the first one I saw which had a specific link on contributing with courses (EDX) required financial contribution in order to host a course there, which is something I assume we don't want. I'm still reading up on it.

**Comment by NukeManDan** [comment]
Keep looking down the list, there are many free options :grin: 

https://www.freecodecamp.org for instance has a very large library of content, and a large base of OSS contribution already, and is OSS itself (including lessons). Here we might give IPFS a lot of visibility just porting some ProtoScool content there.

**Comment by NukeManDan** [comment]
FreeCodeCamp uses https://glitch.com and other robust IDEs and has you submit your code developed there against tests back on the lessons page to check your solutions. This method could also be used on ProtoSchool to simplify (:crossed_fingers: ) tutorial and ProtoSchool development itself.

**Comment by dominguesgm** [comment]
The main concern is the dependency on IPFS to create coding exercises, I have some doubts platforms like _freeCodeCamp_ would feel comfortable in introducing this dependency to provide the possibility of having live coding challenges in an IPFS course. My attempts at using js-ipfs in codesandbox, for example, continue to be unsuccessful 😞.

Nevertheless, if we manage to produce more content, or adapt content, to a format that could be more appropriate for platforms like _freeCodeCamp_, as @NukeManDan said, it would be a great idea to gather more interest towards IPFS.

Formats like theoretical courses, or courses where the user is expected to use his own environment (it would be a great chance to teach IPFS on the _cli_), look to me like great fits for this format. This wouldn't exactly serve as an alternative to ProtoSchool, but instead as a way to bring more people in. Also, we could always plug a "Learn more about IPFS at [ProtoSchool](https://proto.school)" at the end of each lesson there 😄

**Comment by terichadbourne** [comment]
Thanks for your continued research @dominguesgm and to others for the suggestions. 

Just to clarify our focus, what we are researching is whether there is an existing platform that will allow us to build in-browser JavaScript tutorials on IPFS, libp2p etc. more easily and with more features than the system we've built for ourselves. If we found a fully-featured embeddable tool like that, we could stop adding new features to our custom Vue platform. A tool that can't be adapted to support IPFS, libp2p, etc. validation under the hood is a non-starter, as is a tool that won't allow in-browser tutorials (requires command line and use of user's own environment, making content less beginner-friendly and removing our ability to track progress and provided detailed feedback) or one that can't be embedded into our system. The tool we're looking for is not the equivalent of the user-facing sites mentioned in this thread, it's an open-source version of what some of them might use under the hood. 

I fully support the goal of surfacing IPFS and related DWeb education in places folks currently frequent, and would encourage more community members to write articles or tutorials on Medium, freeCodeCamp, etc. because of the great discoverability there, and I agree with @dominguesgm that those pieces could encourage people to head to ProtoSchool for more learning. However, that effort wouldn't achieve the goals of this particular issue.

**Comment by NukeManDan** [comment]
> https://glitch.com, https://codepen.io/

These _might_ be plugin-able, glitch in particular. What freecodecamp does is an option as well: point to use a 3rd party to develop a solution then come back to proto.school to test and get feedback / correct or not indications based on submission.

So instead of spending a lot of time building an in house IDE, we use robust ones that exist already and focus on content creation.

**Comment by mikeal** [comment]
One thing to keep in mind is that, since I wrote the original version of this in about a week, there was no time to fix any usability issues with `js-ipfs` that might have made it easier for people to jump into a coding exercise. As a result, the exercises are setup in a way that abstracts a lot of the work that it takes to instantiate and clear a `js-ipfs` instance.

Some portion of what ProtoSchool abstracts away should just be fixed/simplified in `js-ipfs` itself. The fact that it’s so hard to use `js-ipfs` in these other code editors isn’t necessarily a *ProtoSchool* problem, it could be a *js-ipfs* problem and it’s potentially an indication that getting up and running is too difficult and requires a lot of tooling that makes it difficult to use `js-ipfs` in a lot of environments. For every one of these tutorial platforms there’s dozens, if not hundreds, of similarly challenged environments applications are built in that might want to use `js-ipfs` and may not because it’s too difficult.

PS. I know a few people at Glitch, if we have specific issues and/or questions I can connect whoever is leading this effort with the right folks at Glitch.

**Comment by terichadbourne** [comment]
@dominguesgm has completed his review of alternative coding platforms, with a focus on two types of projects: 
- learning platforms that include both lessons and code editors, such as Chainshot and FreeCodeCamp
- IDEs such as CodeSandbox and Glitch


In brief: 
- With improvements to js-ipfs to make it easier to use in a variety of environments, IDEs like Glitch could be useful in the future for someone who wanted to create a tutorial helping folks build full DApps from start to finish. However, they're not at all appropriate for our current needs. 
- Learning platforms like the open source FreeCodeCamp are closer to being a match for our needs, but the burden of rebuilding existing features not supported by FreeCodeCamp and porting over other features and curriculum far outweighs the feature benefits we'd gain that are useful in our current model. 

Please see the [full notes](https://docs.google.com/document/d/17w9Ni1OP_jP6vhQthLD9ZNPvh19g2-PD0GCEr9sVYo4/edit?usp=sharing) for a much more thorough and nuanced discussion. :)
