### ISSUE TITLE
Reference tutorials by IDs, not shortnames, when caching to localStorage

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#289]
Fix things under the hood so that if we change the name or shortname of a tutorial, the way we cache code in localStorage won't be affected and if a user previously passed it under a different name it will still be passed.

**Comment by terichadbourne** [comment]
This will also require a retroactive fix so that folks who have the currently existing tutorials cached have those caches relabelled in localStorage.

**Comment by terichadbourne** [comment]
As part of this work let's add a clear section to the instructions on the various places things need to be updated if renaming a tutorial. 

We should also add a checklist for maintainers about what to check for when a new tutorial is submitted (for example, adding to the list of tutorials to be checked by Cypress if relevant). That list could potentially live here but be linked to from the `admin` repo.

**Comment by fsdiogo** [comment]
I'm taking a look at this one, and I've found some caveats:

- the tutorial shortname is always constructed based on the path (the tutorial URL), so we don't have it stored anywhere, and even if we did it wouldn't help us because we use the current URL to add it to the navbar and more;
- the keys we're saving in localStorage are based on the tutorial shortname, i.e, the URL, so **the paths are what dictate the shortname and the localStorage keys**;

So, I'm not sure how to create a unique ID and decouple that from the tutorial path, as even in the Lesson component all the localStorage logic is using the current path and nothing more.

Is it OK to ask a tutorial creator to create an URL knowing that the shortname will be derived from it?
