### ISSUE TITLE
Lesson Feedback: Mutable File System - Lesson 2 (Check the status of a directory)

### ISSUE THREAD

**Issue by hackenstacks** [ProtoSchool/protoschool.github.io#305]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
eg https://proto.school/#/blog/01

**What's confusing about this lesson?**
not sure what return your result means
**What additional context could we provide to help you succeed?**
an excerpt of what it means to (return your result)
**What other feedback would you like to share about ProtoSchool?**

**Comment by terichadbourne** [comment]
Thanks so much for the feedback, @hackenstacks! 

You can learn more about [JavaScript returns](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/return) here. 

So that we can make things as clear as possible for future learners, would you mind sharing a bit about your experience level with coding, with JavaScript, and with IPFS?

**Comment by terichadbourne** [comment]
@hackenstacks just circling around to see if that link was helpful in explaining what it means to return a result in Javascript. Please feel free to reopen this issue if you have more questions. 

We have a separate suggestion in #165 to better explain returns.
