### ISSUE TITLE
Mention Unixfs sharding options in Regular Files API tutorial

### ISSUE THREAD

**Issue by daviddias** [ProtoSchool/protoschool.github.io#320]
Suggestion: Cover the Unixfs sharding option. Current docs on it are:

https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#add

`enableShardingExperiment: allows to create directories with an unlimited number of entries currently size of unixfs directories is limited by the maximum block size.`

`shardSplitThreshold (integer, default 1000): specifies the maximum size of unsharded directory that can be generated.`

Why I think it is important? Because without using Unixfs Sharding, users won't be able to transfer directories with a large number of files. Directories with large number of files get clogged in a Bitswap transfer (due to Bitswap 4MB limitation).

**Comment by terichadbourne** [comment]
Thanks for the suggestion @daviddias!  

Curious to know how frequently IPFS users take advantage of this option. We've mostly focused on teaching the basic commands for beginners with the most common gotchas or important setting, linking to the docs for details on other options that they may want to use when they experiment on their own. Based on the beginner-ness of this tutorial, we also haven't introduced Bitswap here. 

@achingbrain What would be your recommendation here based on frequency of usage of the Unixfs sharding option? (Also checking in in case options have changed since the suggestion was made.)
