### ISSUE TITLE
Create Cypress tests for file upload

### ISSUE THREAD

**Issue by dominguesgm** [ProtoSchool/protoschool.github.io#323]
As it currently stands, we use cypress as our testing framework, for which we have tests for every lesson in tutorial 2 and 3.

There is an issue with building tests for the other tutorials, which make use of file upload, which from what I know, Cypress is not able to mock. *However*, with the way we store uploaded files in an array in the `window` object, I believe we can dynamically create a file for testing purposes. See [this link](https://stackoverflow.com/questions/27159179/how-to-convert-blob-to-file-in-javascript), which may be useful.

The biggest driver from this issue, in my opinion, comes from the fact that every time some core functionality is changed - for example how we're changing `Lesson.vue` in #301 - we have to manually run error cases to see if the user code output and validation output are being handled correctly in all cases, which is time consuming and should be automated.

**Comment by terichadbourne** [comment]
Agree it would be great if we could find a way to apply the test to our file upload lessons. And perhaps we'll need a new setup to handle the multiple choice type that no one has used yet as well?

**Comment by terichadbourne** [comment]
Another thing to test for automagically is that all individual lessons are rendering. 

We recently discovered (https://github.com/ProtoSchool/protoschool.github.io/pull/325) that lesson 11 of MFS wasn't because we'd screwed up the path in the router: 
```
{ path: '/mutable-file-system/01', component: T0004L11 }
```
When the user hit the "Next" button from lesson 10 it jumped right to Resources instead of hitting 11. 

Lesson 11 was displayed in the index at http://localhost:3000/#/mutable-file-system but the link to the lesson led to our Page Not Found message. Teaching Cypress to click on every link from that index and confirm the lesson title was visible might be one option for testing.

**Comment by terichadbourne** [comment]
This one was closed unintentionally - #326 actually states that it doesn't close this issue because we still aren't testing solution code for file upload or multiple choice lessons (no one has used the mult choice format yet, but we have tutorials based on file upload). 

The lack of this testing functionality is why we could have accidentally broken MFS lesson 7, which couldn't be tested by Cypress, by merging #301. 

How to mimic uploading an actual file for testing purposes is something we haven't been able to get our heads around yet. Would love your thoughts on it @zebateira. If we can't upload a real file due to browser permissions, maybe we could create some workaround where if the app knows it's cypress and not a real user running the program, it passes in a set value for `files` that's the equivalent of what would be created if we'd uploaded a very small .txt file? ¯\_(ツ)_/¯
