### ISSUE TITLE
Tutorial Feedback Survey with A/B Testing

### ISSUE THREAD

**Issue by zebateira** [ProtoSchool/protoschool.github.io#423]
New Feedback Survey to be presented to the users at the end of the tutorial in the resources page.

### Option A

![image](https://user-images.githubusercontent.com/2353186/79762497-c2deef80-831a-11ea-9381-332e8d0dd9b8.png)

### Option B
![image](https://user-images.githubusercontent.com/2353186/79762566-d1c5a200-831a-11ea-8aa2-6abad43a210e.png)

Figma: https://www.figma.com/file/lnCeFi9O1PIgxMdKcgHIcM/ProtoSchool-Website?node-id=93%3A1699

- [x] Build simple A/B testing util using local cache (consider [countly's support for a/b testing](https://count.ly/plugins/ab-testing))
- [x] Feedback SurveyA UI
   - [x] Option A
   - [x] Option B
- [x] Track responses to Countly
- [x] Do not show feedback survey again if the user comes back to the page again after they filled the form or it has been dismissed
   - Cache each question response (boolean, the actual response is not cached): this way we can ask them only the questions they haven't filled in

**Comment by zebateira** [comment]
@terichadbourne so I started to integrate with Countly and I think we need to discuss how we will use the data that we will track.

As fas as I could understand, countly only allows us to check the count for a custom event. So in this case, we will not be able to see clearly on the graph what tutorial got what score for what question.
Examples: How many 4's did I get to the question number 3? How many 1's did I get for the tutorial x?
Do we want to ask these questions?

I think I need to know exacly what are the questions we need to answer here so that I can integrate with Countly with that in mind.

I've made an initial integration with countly in the branch `feat/feedback-survey-form` which you can load up and answer some questions to send events to countly. This is the current event entries we have: https://countly.proto.school/dashboard#/5d52d37b700a111dd3ec5ede/analytics/events

There's also another way for us to access the entirety of the data through here: https://countly.proto.school/dashboard#/5d52d37b700a111dd3ec5ede/manage/db/countly_drill/drill_eventsd47433b332b614f9c4e652fefc2f747deaf19b3b
In this case, we could do a DB export and could process the export and get something like this:

```json
[
   {
        "path":"/data-structures/resources",
        "tutorial":"Data Structures",
        "question":"1. Understanding of the concepts",
        "answer":4
   },
   {
        "path":"/data-structures/resources",
        "tutorial":"Data Structures",
        "question":"2. Excitement to continue learning",
        "answer":5
   },
   {
        "path":"/data-structures/resources",
        "tutorial":"Data Structures",
        "question":"3. Where to go next",
        "answer":4
   },
   ...
]
```

Which we could load up in spreadsheets and make some graphs.

**Comment by terichadbourne** [comment]
Yeah, the built-in display options are lacking, but "Drill" is useful. So for example... 

Here's a bar graph showing how many times each rating was given to question 2 for the Anatomy of a CID tutorial. We'd have to create 3 of these, one for each question, for each tutorial. 
![image](https://user-images.githubusercontent.com/19171465/80746833-7d77aa80-8af0-11ea-8d26-bd29e976c347.png)

Here's how many times each answer was given for Question 1 across all tutorials. We'd need one of these for each question. 
![image](https://user-images.githubusercontent.com/19171465/80746972-aef07600-8af0-11ea-901d-05f9d6b23856.png)

It's also available as percentages instead of counts of responses as a pie chart like this: 
![image](https://user-images.githubusercontent.com/19171465/80747121-eeb75d80-8af0-11ea-8069-26235167712a.png)

And unless my math skills are failing me, we could do this math... 
(3 x 33%) + (4 X 50%) + ( 5 x 17%) = an average rating of 3.8 for question 1 across all tutorials

I think what we actually care about is the average rating for each question, both across all tutorials and for a specific tutorial. Ultimately I think the data we care about is: 

| Average Rating (1-5) | Overall | Tutorial A  | Tutorial B | Tutorial C | 
| --- | --- |--- |--- |--- |
| Understanding of concepts | 4.3 | 3.7 | 2.6 | 4.5 |  
| Excitement to continue learning | 3.7 | 4.1 | 3.9 | 3.5 | 
| Knows where to go next |  3.8 | 2.3 | 4.0 | 4.5 |  


Even better to help us judge how meaningful the data is (excuse the non-existent math):

| Average Rating (1-5) (number of respondents) | Overall | Tutorial A  | Tutorial B | Tutorial C | 
| --- | --- |--- |--- |--- |
| Understanding of concepts | 4.3 (30 respondents) | 3.7 (10) | 2.6 (10) | 4.5 (10) |  
| Excitement to continue learning | 3.7 (25 respondents) | 4.1  (8) | 3.9 (9) | 3.5 (4) | 
| Knows where to go next |  3.8 (24 respondents)  | 2.3  (8) | 4.0 (8)  | 4.5 (4) |  

And of  course the overall rating for each question is an average of all original responses, not an average of the tutorial averages. 

Countly does have a formula feature but so far it's not seeming quite flexible enough for some of the math I'd like to do for this and other data.

**Comment by zebateira** [comment]
@terichadbourne ah great, I'm glad the drill feature is enough. Awesome breakdown you've presented. I like this.

Let me know if you need anything else to be tracked to countly. I'll continue with the UI implementation + second option of the form.
