### ISSUE TITLE
Bug: Newsletter subscription blocked on Firefox 

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#441]
Newsletter signup apparently blocked on Firefox. See https://twitter.com/raybachas/status/1263507550135296002?s=21

@zebateira Mind taking a look after the weekend to see if you can reproduce and diagnose?

**Comment by zebateira** [comment]
@terichadbourne can't reproduce on Firefox both on Mac and Windows.
I do see a warning related to what he mentioned in the tweet but it doesn't affect the functionality.

I've also noticed an email that subscribed around the time he tweeted that seems to be his.
So I'd suggest to follow up with him.

**Comment by terichadbourne** [comment]
I've tried both our embedded signup form at (https://proto.school/#/news) and the independent Mailchimp form (https://school.us4.list-manage.com/subscribe?u=41e9e493c56c3865870435d91&id=967f7cf514) on Firefox 72.0.2 (64-bit) and both appear to work. I get a cookie warning in the console only on the embedded form but it doesn't block functionality. Will respond on Twitter and ask him to share more details here.

**Comment by raymundovr** [comment]
Hello :)

I have Firefox 76.0.1
In attachment a screenshot of the timeout while trying to subscribe to your newsletter.

![Screenshot 2020-05-27 at 15 59 45](https://user-images.githubusercontent.com/108420/83029572-18ea3580-a033-11ea-8081-3890dcf56d52.png)

**Comment by zebateira** [comment]
Hey @raymundovr thank you for the help tracking this!
I was able to reproduce it now. If I'm not mistaken it's because you've enabled "Enhanced Tracking Protection" in Firefox preferences?

<img width="704" alt="Screenshot 2020-05-27 at 4 23 38 PM" src="https://user-images.githubusercontent.com/2353186/83040023-b72bca80-a036-11ea-9280-4b2e30bb0f26.png">

I tried it with the option "Standard" and it worked (which is the default setting on firefox) but it failed with the "Strict" mode.

Can you confirm this is the issue?
I'll look into a solution for this.

**Comment by zebateira** [comment]
It seems that this is a somewhat expected behaviour when using **Strict** mode.

<img width="848" alt="Screenshot 2020-05-27 at 4 54 44 PM" src="https://user-images.githubusercontent.com/2353186/83043511-e47a7780-a03a-11ea-9f0f-3d82f011e46c.png">

From here: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_adjust-your-global-enhanced-tracking-protection-settings

> Strict makes pages load faster, but may break some buttons, forms, and login fields.

Makes sense. I think we can make the form open a new tab (good old form post method) to avoid this issue. This way we can allow users to block what they want but still provide all the functionality.

**Comment by zebateira** [comment]
hey @raymundovr we just pushed a fix for this.
Thank you for your help on this one!

Let us know if you have any more feedback.

**Comment by raymundovr** [comment]
Very nice PR :)
Thank you very much for solving this.
