### ISSUE TITLE
Feature: Tutorial project filter

### ISSUE THREAD

**Issue by zebateira** [ProtoSchool/protoschool.github.io#450]
We want to be able to filter the tutorial list by project (IPFS, Multiformats, Filecoin, etc).
For this we can add a dropdown selector on top of the tutorials list in the tutorials page.

#### Closed Filter
![image](https://user-images.githubusercontent.com/2353186/84927852-5cc9db00-b0c5-11ea-9b82-c5123b54e507.png)

#### Opened Filter
![image](https://user-images.githubusercontent.com/2353186/84927837-53407300-b0c5-11ea-926e-da57843be9a5.png)

**Comment by terichadbourne** [comment]
Note that this will be ordered courses as opposed to filtering by project, since many introductory lessons fit into multiple categories. (eg Decentralized Data Structures, labelled as DWeb Concepts, and Anatomy of a CID, labelled as Multiformats). 

We should discuss whether we want to order these in the filter alphabetically, by popularity, by our own desires to drive traffic, or by how many tutorials exist in each course. My current suggestion, which meets all of these expect alphabetizing) would be: 
- All (if it's actually shown here)
- IPFS
- Filecoin 
- Multiformats

Here's the data for `courses.json` when we're ready (this assume we merge the Filecoin tutorial #0007 first):

```json
{
  "all": [
    "0001",
    "0004",
    "0005",
    "0002",
    "0003",
    "0006",
    "0007"
  ],
  "featured": [
    "0001",
    "0007",
    "0004",
    "0005"
  ],
  "ipfs": [
    "0001",
    "0004",
    "0005",
    "0002",
    "0003",
    "0006"
  ],
  "filecoin": [
    "0001",
    "0007",
    "0006"
  ],
  "multiformats": [
    "0001",
    "0006"
  ]
}
```

**Comment by terichadbourne** [comment]
To do: 

- [ ] Update tests based on switch to cards (@terichadbourne)
- [ ] Add new / updated flags to cards on both homepage and tutorials page (@zebateira)
