### ISSUE TITLE
Bug: incorrect metadata rendering 

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#526]
[This tweet](https://twitter.com/filecoin/status/1292919017833889792?s=21) links to the filtered Filecoin course but the Twitter card shows as the homepage (and not even with the correct homepage title):

![8C00D7CC-F366-44F0-9F7D-86F7DBFBD9E9](https://user-images.githubusercontent.com/19171465/90141726-801da900-dd49-11ea-8475-009ac6bb6366.png)

@zebateira Any idea what could be going wrong?

**Comment by zebateira** [comment]
I think this is what's going on:

The original url on the tweet is using hash routing. The redirect to the new routes is done client side, this means that search engines and social media cards will always parse the url `/#/tutorials?course=filecoin` and think those old links point to the root `/` always, because no redirect is done. The only way I can think of to allow this to work is to add server side redirect for this, basically list all the routes (probably exclude lessons and resources page) in the netlify config file, and then migrate this list to fleek later when we do that migration.

If you test with this url: https://proto.school/tutorials/?course=filecoin
You will see the metatags for the `/tutorials` page. This is better than the homepage, but still not the filecoin tutorials metadata. So I think this is not working properly yet.

The reason the homepage metadata is wrong is because that code change hasn't been merged yet #521 

I'll work on the course metadata issue, but let me know if old links with hash routes are a priority to fix as well.

**Comment by zebateira** [comment]
Regarding the course metadata: when accessing `/tutorials?course=filecoin` the metadata returned is the one pre-rendered in the tutorials html file. I thought crawlers would run JS and so the vue metadata package would kick in and the correct metadata would be used. But this does not seem to be the case. So I think the way to do this would be to go with Andrew's idea to create separate `/courses/*` pages like `/courses/filecoin` - it seems to be the only way to achieve different metadata for each course.

**Comment by terichadbourne** [comment]
Thanks for that last comment. Was just about to flag the issue of specific course links showing the tutorials page instead of the special course description. 

I've sent an email to Labbers about how our new URLs are needed to produce the new social cards and flagged in Slack to marketing/comms folks most likely to help with promotion. I suspect we won't see much sharing of old URLs after that communication, but we can keep an eye on it and circle around when you're back on next steps.
