### ISSUE TITLE
Update metadata for porto.school (forwarded)

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#539]
We own porto.school thanks to our Moxy friends and it forwards to proto.school. 

Searching for the typo proto.school in Google (incognito) gets this, which is awesome but using outdated metadata:
![94295BC9-FAF1-49D5-8AB7-6E57FCB9DE9A](https://user-images.githubusercontent.com/19171465/90770272-823eb500-e2bf-11ea-8291-db9a17758db4.jpeg)

I’m not sure if a change in our code or the DNS setup could get that up to date, matching the metadata for our homepage.

Searching just for the typo portoschool without the dot gets exclusively listings for schools in Porto. 

![B65F583B-D865-4E0B-AE72-DE6D33E6078D](https://user-images.githubusercontent.com/19171465/90770397-bade8e80-e2bf-11ea-8e15-7d61e3dc7a0a.jpeg)

I assume there’s not much we can do about this case.

**Comment by terichadbourne** [comment]
@zebateira Would you mind checking with the Moxy crew whether there's an option to update the metadata for porto.school? Probably not super high priority since you're more likely to arrive at the site from typing the URL wrong that way than typing a search query wrong that way.

**Comment by zebateira** [comment]
I could be wrong, but I think this should work automatically since the domain `porto.school` is simply configured in our DNS server, meaning google crawler _should_ follow the redirect and get the latest metadata. It just might be a caching issue on google's side caused by low number of accesses of `porto.school`.

Using metatags tool you get the correct metadata: 
![image](https://user-images.githubusercontent.com/2353186/101009874-0b6db500-355a-11eb-9382-a0cada150329.png)


In any case, I could be wrong but I don't believe it is possible to easily add metadata before the redirect is performed.
