### ISSUE TITLE
Lesson Feedback%3A Mutable File System - Lesson 2 (Check the status of a directory)

### ISSUE THREAD

**Issue by moratsam** [ProtoSchool/protoschool.github.io#568]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
https://proto.school/mutable-file-system/02

**What's confusing about this lesson?**
How do I run this code natively on my own node?

**What additional context could we provide to help you succeed?**
Explanation how to run this code natively.

**What other feedback would you like to share about ProtoSchool?**
It's too basic, lots of important questions remain unaddressed.

**Comment by terichadbourne** [comment]
Thanks for the feedback @moratsam! In order to keep our content accessible, we've chosen to use examples that folks can play with right in the browser. However, if you prefer learning materials that are a bit more hands-on on your own machine, I'd recommend exploring the [how-to section of the IPFS Docs site](https://docs.ipfs.io/how-to/). It links to a number of repos with sample code, including this one on the [Mutable File System](https://github.com/ipfs/js-ipfs/tree/master/examples/browser-mfs) specifically.
