### ISSUE TITLE
Lesson Feedback: Blog - Lesson 6 (List posts chronologically with a chain of links)

### ISSUE THREAD

**Issue by theNvN** [ProtoSchool/protoschool.github.io#596]
There might be a bug in the lesson 6 of  "Blogging on Decentralized Web" lesson.

URL: https://proto.school/blog/06

The Submitting of the solution to the exercise is not working. No errors/success message displayed....nothing happens.

Browser: Brave, Version 1.19.86

**Comment by zebateira** [comment]
hello @theNvN!
Thank you for the bug report.

I've just tested this on Brave 1.19.86 and it worked with the solution code.
Do you mind sharing the code you submitted?

**Comment by theNvN** [comment]
Hi @zebateira 
This is the code
```
/* globals ipfs */

const run = async () => {
  const natCid = await ipfs.dag.put({ author: "Nat" })
  const samCid = await ipfs.dag.put({ author: "Sam" })

  // Modify the blog posts below

  const treePostCid = await ipfs.dag.put({
    content: "trees",
    author: samCid,
    tags: ["outdoor", "hobby"]
  })
  const computerPostCid = await ipfs.dag.put({
    content: "computers",
    author: natCid,
    tags: ["hobby"]
    prev: treePostCid
  })
  const dogPostCid = await ipfs.dag.put({
    content: "dogs",
    author: samCid,
    tags: ["funny", "hobby"],
    prev: computerPostCid
  })

  const outdoorTagCid = await ipfs.dag.put({
    tag: "outdoor",
    posts: [treePostCid]
  })
  const hobbyTagCid = await ipfs.dag.put({
    tag: "hobby",
    posts: [treePostCid, computerPostCid, dogPostCid]
  })
  const funnyTagCid = await ipfs.dag.put({
    tag: "funny",
    posts: [dogPostCid]
  })

  return dogPostCid
}

return run
```

Code seems to process/load something (Submit btn is disabled for a moment), but no feedback, error or success, is outputted.

**Comment by zebateira** [comment]
thank you for sharing that!
I can see the issue now: you're missing a comma in the `computerPostCid` variable creation, where `tags: ["hobby"]` should end with a comma. See final correct correct code:

```
/* globals ipfs */

const run = async () => {
  const natCid = await ipfs.dag.put({ author: "Nat" })
  const samCid = await ipfs.dag.put({ author: "Sam" })

  // Modify the blog posts below

  const treePostCid = await ipfs.dag.put({
    content: "trees",
    author: samCid,
    tags: ["outdoor", "hobby"]
  })
  const computerPostCid = await ipfs.dag.put({
    content: "computers",
    author: natCid,
    tags: ["hobby"],
    prev: treePostCid
  })
  const dogPostCid = await ipfs.dag.put({
    content: "dogs",
    author: samCid,
    tags: ["funny", "hobby"],
    prev: computerPostCid
  })

  const outdoorTagCid = await ipfs.dag.put({
    tag: "outdoor",
    posts: [treePostCid]
  })
  const hobbyTagCid = await ipfs.dag.put({
    tag: "hobby",
    posts: [treePostCid, computerPostCid, dogPostCid]
  })
  const funnyTagCid = await ipfs.dag.put({
    tag: "funny",
    posts: [dogPostCid]
  })

  return dogPostCid
}

return run
```

Although you are absolutely right that it should give some feedback about the error!
We'll work on a fix for this so that all syntax errors are picked up.

**Comment by theNvN** [comment]
@zebateira Ah, I see a petty mistake from my side. It works now. I was expecting an error message/highlight, so didn't look up much. Thank you very much for your effort!

**Comment by zebateira** [comment]
Hey @theNvN, just an update that you should have an error feedback now when submitting the code.
Although this is not ideal because you don't have an easy way to know _where_ the error is if it's a syntax error for example.
So we'll keep this open until we can show inline errors in the code editor. You can track the issue here: https://github.com/ProtoSchool/protoschool.github.io/issues/597

Thank you once again for the feedback and for using ProtoSchool! 🙏
